### ISSUE TITLE
Create New Experiment

### ISSUE THREAD

**Issue by jadeyliu939** [iter8-tools/kiali-ui#4]
Create New Experiment
1. From the Action dropdown  in Experiment view
2. From the Action dropdown in Service View

UI design for Create New Experiment

<img width="1419" alt="Screen Shot 2020-03-31 at 5 00 44 PM" src="https://user-images.githubusercontent.com/4615187/78074773-46876b00-7371-11ea-926a-5453ff7583f8.png">
<img width="1405" alt="Screen Shot 2020-03-31 at 5 01 09 PM" src="https://user-images.githubusercontent.com/4615187/78074783-4be4b580-7371-11ea-8199-1f3403913039.png">

**Comment by fabolive** [comment]
Copying and augmenting the feedback provided by @sriumcp:

- Use the term `Assessment Criteria` instead of `Success Criteria`
- Assessment Criteria appears before Advanced Traffic Controls
- Advanced Traffic Controls are all optional
- Use the terms `Threshold Type` and `Threshold Value` instead of `Tolerance Type` and `Tolerance` respectively. 
- `Threshold Type` can take on two possible values -- absolute and relative -- instead of "threshold" and "delta" respectively.
- Sample size should not be exposed to user (we will use sensible defaults for all advanced traffic controls including user-facing ones, so that the user can skip this section entirely if she/he wants to)

**Comment by jadeyliu939** [comment]
Please see attached screen for updated version based on @sriumcp suggestions. 
<img width="1397" alt="Screen Shot 2020-04-08 at 5 57 13 PM" src="https://user-images.githubusercontent.com/4615187/78839119-b75c0200-79c5-11ea-8421-768ef2f404ea.png">

Here is the Advanced Options:

<img width="1398" alt="Screen Shot 2020-04-08 at 6 02 27 PM" src="https://user-images.githubusercontent.com/4615187/78839126-b9be5c00-79c5-11ea-9b07-33927ca90b91.png">

**Comment by sriumcp** [comment]
@jadeyliu939 Updated version looks great.

I have one more minor comment -- `Traffic step size` makes sense only if the Algorithm is `check_and_increment`. 

So -- maybe it might be better to display the algorithm on the left, and show the step size param on the right with the understanding that step size is only displayed if the algorithm is `check_and_increment`

**Comment by jadeyliu939** [comment]
Update [Kiali issue 2629](https://github.com/kiali/kiali/issues/2629)

**Comment by jadeyliu939** [comment]
@sriumcp 

In Advanced Options, the "Traffic Step Size" will be programmatically show/hide depending on the algorithm selected.

**Traffic Step Size Shown for "Check and Increment"** 
![Screen Shot 2020-04-09 at 2.28.53 PM.png](https://images.zenhubusercontent.com/577f9bbabf93871ccd9dbd9f/4aec65e6-dd92-4c08-984a-4a3035942531) 

**Traffic Step Size hidden for all others**
![Screen Shot 2020-04-09 at 2.29.03 PM.png](https://images.zenhubusercontent.com/577f9bbabf93871ccd9dbd9f/31a0b982-bb3d-4759-bb95-3d939a519d8f)

**Comment by jadeyliu939** [comment]
Convert to Wizard

![Screen Shot 2020-04-09 at 6.20.01 PM.png](https://images.zenhubusercontent.com/577f9bbabf93871ccd9dbd9f/8b23c5e2-ff3d-4c1d-baee-bcbe29829e91)

**Comment by jadeyliu939** [comment]
PR were merged and is now include in Kiali 1.18.1 release
